### ISSUE TITLE
Confusing which camera to use for ScreenToWorldPoint, ViewportToWorldPoint, etc.

### ISSUE THREAD

**Issue by bburrough** [Looking-Glass/HoloplaySDK_Issues#42]
When bringing code from other non-Looking-Glass projects over, it's common to see Camera.main.ScreenToWorldPoint(Input.mousePosition).  However, when using the Holoplay SDK, this doesn't work.  I found by digging through the Holoplay.cs that I can use LookingGlass.Holoplay.Instance.cam.ScreenToWorldPoint(Input.mousePosition) instead.

// This doesn't work as it typically would
Camera.main.ScreenToWorldPoint(Input.mousePosition)

// This does
LookingGlass.Holoplay.Instance.cam.ScreenToWorldPoint(Input.mousePosition)

It would be helpful if the Holoplay SDK was compatible with existing code that uses Camera.main.

**Comment by bburrough** [comment]
To expand on this a bit further...the SDK is kind of obfuscating what the right thing to do is.  Using Camera.main returns invalid results, but unless someone digs through Holoplay.cs to see how screen positions are converted to world space, they wouldn't know that there's an entirely separate camera for that purpose.

e.g. Do we really need two cameras here (line 92 in 1.0.0...)

		// not in inspector
		[System.NonSerialized] public Camera cam;
		[System.NonSerialized] public Camera lightfieldCam;
		const string lightfieldCamName = "lightfieldCam";
		[System.NonSerialized] public Calibration cal;
		bool debugInfo;

**Comment by grenappels** [comment]
you're right, it is a bit unclear. adding a MainCamera tag shouldn't hurt, and will make life easier for everyone, so i'll plan on doing that.

to explain a bit about the lightfieldCam: the need for a second camera is for post-processing the quilt into the lightfield output. it's basically just a pass through camera for that purpose. the thing is, if you put other post-processing effects on the Holoplay Capture gameobject, it ends up running those post-process effects on the final lightfield output as well, completely messing up the output! so the split is necessary.

**Comment by alxdncn** [comment]
Fixed in 1.3.0
