### ISSUE TITLE
is the cameraCapture is compatible with HDRP

### ISSUE THREAD

**Issue by dpotuznik** [Looking-Glass/HoloplaySDK_Issues#43]
i try to use the HoloCapture on the default scene come with the HDRP and it's not seem to work.

it is compatible with HDRP ?

thank you have nice day.
Best Regards
Daniel

![image](https://user-images.githubusercontent.com/11964995/55680179-7d6da100-5916-11e9-8e21-e5a118431fa1.png)

**Comment by grenappels** [comment]
no it is not -- currently implementing this is pretty low priority, as rendering performance is already pretty stifled by the need for ~45 renders per frame, and we're focusing on optimizations for now.
