### ISSUE TITLE
Preview does not work with Unity

### ISSUE THREAD

**Issue by reneschulte** [Looking-Glass/HoloplaySDK_Issues#45]
I'm following the video using Unity 2018.3.3f1
https://vimeo.com/326896601 

The Toggle Preview does not work. I've setup the display correctly as extended and I can run the sample binary mentioned in the setup guide with the scene showing the button usage. I can also build an example scene mentioned in the video and run the exe file fine on the LG. Only the preview in Unity is not working which is a bit annoying as the workflow is much nicer with the preview.

**Comment by reneschulte** [comment]
Update. Also tried with the exact same version shown in the video 2017.4.23f1 and still no luck. :(

**Comment by reneschulte** [comment]
Update 2. Seems I can get Unity 2017 to work when I move the Unity to my 2nd monitor which is set to 100% scale, even when my 1st monitor is at 200% scale. LGK is my 3rd monitor setup. But Unity 2018 only works when all monitors are set to 100%.

**Comment by alxdncn** [comment]
Kyle is looking into this! We'll update as soon as we can.

**Comment by fractalfrenzy** [comment]
I am also having this issue.

**Comment by reillydonovan** [comment]
When I preview in Unity the preview window is offset by about 1/5 of the width of the display, test apps outside of Unity work fine, any suggestions?

**Comment by alxdncn** [comment]
Unfortunately we have been unable to make the preview window compatible with monitor scaling. Typically, only the monitor that has Unity running on it needs to be set to 100% scaling, which seems like that worked for you @reneschulte. We wish we could do more for this but, unless we make our own GL context to render the preview window in, we're limited by Unity here!

**Comment by reneschulte** [comment]
Makes sense @alxdncn Thanks for the extra context.
