### ISSUE TITLE
how to create a quilt from a video

### ISSUE THREAD

**Issue by fractalfrenzy** [Looking-Glass/HoloplaySDK_Issues#46]
I have downloaded a video from Vimeo in the quilt format. Now I am trying to connect it to Holoplay to play within Unity.  I saw a guide that showed how to link the video to a RenderTexture via the Unity VideoPlayer component and then connect the RenderTexture to Holoplay.  Unfortunately, that seems to be for an older version of the SDK.  It currently doesn't seem possible to use a RenderTexture as the override quilt.  How can I play a video as a quilt?  Thank you.

**Comment by alxdncn** [comment]
Sorry about that! I am aware of this bug and will be fixing it for the next release. The Override Quilt field is set to be a Texture2D, but should be a Texture (which is the class RenderTexture inherits from). For now, if you find the override quilt in the Holoplay.cs script and change Texture2D -> Texture, it should work fine!

**Comment by alxdncn** [comment]
The release version will be v1.2.0.
