### ISSUE TITLE
Extended UI not working unless 2nd monitor is 4k

### ISSUE THREAD

**Issue by justonia** [Looking-Glass/HoloplaySDK_Issues#47]
When I build and run the Extended UI demo in Unity 2019.1 the holo display shows a distorted non-3D image in the upper 2/3rds of the screen if the main display is not 16:9. It shows a cut off version of the scene in the holo display if, for instance, the main display is set to 1920x1080.

**Comment by justonia** [comment]
It's possible it's related to this issue:

https://issuetracker.unity3d.com/issues/loading-second-display-on-2-different-monitor-setups-shrinks-the-higher-resolution-display-to-lower-resolution-displays-size

**Comment by alxdncn** [comment]
Hi @justonia, what are your monitor scaling settings set to? We haven't seen this exact behavior before, but we have seem many issues relating to screen scaling.

**Comment by justonia** [comment]
I'm on a Macbook Pro with a Vega Pro 20. My primary monitor is an unscaled ultrawide, 3440x1440. I have other monitors with different scaling, but my first test to see what was going on was disconnecting them (and disabling the Macbook screen) and only having the ultrawide and the Looking Glass plugged in. Same problem.

**Comment by alxdncn** [comment]
Ah I see! Unfortunately Unity doesn't support multi-display on Mac -- this has been a thorn in our side for a long time now. There should be a notification on the ExtendedUI component, did that not come up for you?

Our upcoming SDK release (v1.2.0) will have a roundabout solution for Mac that actually splits each monitor off into separate builds that communicate with each other. That works, but it requires a bit more careful implementation. Hopefully it will work for your purposes, I could send you an experimental release if there's a time pressure!

**Comment by justonia** [comment]
Sorry I should have mentioned, I develop on Windows via Bootcamp.

**Comment by alxdncn** [comment]
We have never tested that setup, I'll try to do some tests on our end and see if we uncover something.

**Comment by justonia** [comment]
There shouldn't be anything different about the setup, Bootcamp doesn't do anything when it comes to GPU/CPU/etc. But you never know I suppose.

**Comment by alxdncn** [comment]
Fixed in 1.2.1 on Unity 2019.3 or later.
