### ISSUE TITLE
Holoplay Capture doesn't capture in Unity 2019.2.17, macOS

### ISSUE THREAD

**Issue by Albert** [Looking-Glass/HoloplaySDK_Issues#50]
macOS ver 10.14.6

<img width="846" alt="Screen Shot 2020-02-14 at 11 33 58 AM" src="https://user-images.githubusercontent.com/19919/74555280-3e35b680-4f10-11ea-980b-3ee85bb83185.png">

@nolanfilter can add more details if he has any.

**Comment by Albert** [comment]
This report occurred in HoloPlay Unity SDK ver 1.2.1

**Comment by alxdncn** [comment]
Fixed in 1.3.0
