### ISSUE TITLE
Feature request to URP support

### ISSUE THREAD

**Issue by zabaglione** [Looking-Glass/HoloplaySDK_Issues#53]
Since the built-in render pipeline will be non-standard after Unity 2020.1, the we would like to support the Universal Render Pipeline.

**Comment by alxdncn** [comment]
This is planned for version 1.5.0 of the plugin.

**Comment by dwcy** [comment]
Having same issue. Any timeline for v 1.5.0?

**Comment by gespona** [comment]
Hi ! I see v1.5.0 is out there but is it including URP support? If not do you have any ETA?

**Comment by alxdncn** [comment]
We hit a real issue with this with windowing in particular. We have URP rendering a quilt, but blitting that to the screen and applying the necessary shader is non-trivial in URP.

We've committed to an overhaul of our window setup that will unlock URP - that will be Unity plugin 2.0 and is scheduled for end of June.

In the interim, the team is trying to put together an alpha version that has URP support, but it'll be primarily useful for recording quilt videos rather than running apps in real-time. We'll make a post about that in Discord if it becomes available!

**Comment by EyezLee** [comment]
> We hit a real issue with this with windowing in particular. We have URP rendering a quilt, but blitting that to the screen and applying the necessary shader is non-trivial in URP.
> 
> We've committed to an overhaul of our window setup that will unlock URP - that will be Unity plugin 2.0 and is scheduled for end of June.
> 
> In the interim, the team is trying to put together an alpha version that has URP support, but it'll be primarily useful for recording quilt videos rather than running apps in real-time. We'll make a post about that in Discord if it becomes available!

Good to know holoplay unity sdk is not abandoned. When can we expect to support HDRP? Thank you!

**Comment by alxdncn** [comment]
Hi @EyezLee! HDRP support is even more difficult than URP - there, we hit _massive_ frame rate issues. I've had many conversations with Unity over the past few months about how to proceed, but there's not a clear path forward until they start better supporting multi-view rendering for more than 2 views. The alternative would be to modify the render stack and maintain a custom fork of the HDRP, which has a number of downsides and may cause several shaders that rely on view position to break.

We're looking at supporting HDRP for quilt video recording - do you need it for real-time or would that fulfill your needs?

**Comment by EyezLee** [comment]
> Hi @EyezLee! HDRP support is even more difficult than URP - there, we hit _massive_ frame rate issues. I've had many conversations with Unity over the past few months about how to proceed, but there's not a clear path forward until they start better supporting multi-view rendering for more than 2 views. The alternative would be to modify the render stack and maintain a custom fork of the HDRP, which has a number of downsides and may cause several shaders that rely on view position to break.
> 
> We're looking at supporting HDRP for quilt video recording - do you need it for real-time or would that fulfill your needs?

Hi @alxdncn ! Thanks for your detailed reply. Yes real-time is my need.

**Comment by alxdncn** [comment]
For those who land on this, we have an experimental release of our plugin with URP support. Currently, it only supports capturing videos and screenshots because of some windowing issues that require a major refactor. Please email me at alex.duncan@lookingglassfactory.com for more information!

**Comment by alxdncn** [comment]
We now have publicly released an alpha version of the plugin with limited URP support, available [here](https://docs.lookingglassfactory.com/developer-tools/unity/2.0-alpha).
