### ISSUE TITLE
Getting below error on example scenes from Holoplay SDK

### ISSUE THREAD

**Issue by E-Yogi** [Looking-Glass/HoloplaySDK_Issues#57]
![image](https://user-images.githubusercontent.com/74641292/99487017-68c70b00-298b-11eb-9a35-01b2e4eb3520.png)

**Comment by alxdncn** [comment]
What version of Unity are you on @E-Yogi? They didn't used to have Vector2Int but added it some time ago, I believe in 2017.

**Comment by alxdncn** [comment]
This seems to be a documentation issue rather than an implementation issue - being clearer about what versions of Unity we support.
