### ISSUE TITLE
Changing Holoplay Volume dimensions in Unity 3D

### ISSUE THREAD

**Issue by wtesler** [Looking-Glass/HoloplaySDK_Issues#58]
The Holoplay volume in Unity3D seems to have an aspect ratio such that width > height, like in the given image:

![Annotation 2021-01-14 172934](https://user-images.githubusercontent.com/2490505/104661455-2a4d8400-568e-11eb-9363-a0f4cfcd687d.png)

How can I change the volume dimensions to have a 0.75 aspect ratio like the Portrait has? I can't seem to find the options on the Holoplay object to be able to do that.

**Comment by alxdncn** [comment]
Hi there! The plugin defaults to the aspect of the 8.9", which was our most common display. We'll need to change it in the next release.

I think having a drop down that simulates the aspect for whatever device you're using when none is detected would be great!

**Comment by alxdncn** [comment]
Provided options for emulating the aspect of different devices in version 1.4.0.
