### ISSUE TITLE
Holoplay SDK Unity for Looking Glass Portrait Support?

### ISSUE THREAD

**Issue by irfanbisyr** [Looking-Glass/HoloplaySDK_Issues#60]
Good Evening,

I'm getting trouble in getting Looking Glass Portrait work for Unity3D. Am I doing something wrong in the display settings or is it not supported yet?

![Capture](https://user-images.githubusercontent.com/51110669/109773427-879f9380-7c42-11eb-81ae-e8e81a9b24a1.PNG)

**Comment by irfanbisyr** [comment]
Sorry I'm using the older Holoplay Service (1.1.3). Changing to the newer version (1.2.0) fixes the issue.

**Comment by alxdncn** [comment]
Glad this got sorted!
